apiVersion: v1
kind: Service
metadata:
  name: addition-client-service
  labels:
    app: addition-client-service
spec:
  type: LoadBalancer
  ports:
  - port: 8100
    name: http
  selector:
    app: addition-client-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addition-client-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: addition-client-service
        version: v1
    spec:
      containers:
      - name: addition-client-service
        image: us.gcr.io/service-mesh-istio-example/addition-client-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8100